services:

  user_service_mongodb:
    image: mongo:6.0.3
    volumes:
      - user_service_mongodb_container:/data/db
    logging:
      driver: 'json-file'
    ports:
      - "27017:27017"

  user_service_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  user_service:
    build: .
    depends_on:
      - user_service_mongodb
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - user_service_mongodb
    env_file: ".env"
  
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user_service
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
    command: ["npm", "start"]

volumes:
  user_service_mongodb_container:
