services:

  users-mongo-service:
    image: mongo:6.0.3
    volumes:
      - users-mongo-service_container:/data/db
    logging:
      driver: 'json-file'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"

  user_service_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  user_service:
    build: .
    environment:
      - MONGO_HOST=mongo
      - MONGO_PASSWORD=pass
      - MONGO_USER=user
    image: users-img
    container-name: users-app
    depends_on:
      - users-mongo-service
    ports:
      - "5000:80"
    volumes:
      - .:/code
    links:
      - users-mongo-service
    env_file: ".env"

volumes:
  users-mongo-service_container:
