services:
  user_service:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/code
    links:
      - user_service_mongodb

  user_service_mongodb:
    image: mongo:5.0
    volumes:
      - user_service_mongodb_container:/data/db
    logging:
      driver: none
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    logging:
      driver: 'json-file'
      options:
        max-size: "10m"
        max-file: "3"

  event_consumer:
    build: .
    command: python /code/app/event_consumer.py
    volumes:
      - .:/code
    depends_on:
     - rabbitmq 

volumes:
  user_service_mongodb_container:
