services:

  user_service_mongodb:
    image: mongo:5.0
    volumes:
      - user_service_mongodb_container:/data/db
    logging:
      driver: 'json-file'
  
  user_service_rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  user_service:
    build: .
    depends_on:
      - user_service_mongodb
    ports:
      - "5000:80"
    volumes:
      - .:/code
    links:
      - user_service_mongodb

volumes:
  user_service_mongodb_container:
