apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress-resource
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: users.nicolascerpa.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-users-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 80
