apiVersion: v1
kind: Service
metadata:
  name: <your_name>-mongo-service
spec:
  type: ClusterIP
  selector:
    app: <your_name>-mongo-app
  ports:
    - port: 27017

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <your_name>-mongo-statefulset
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: <your_name>-mongo-app
  serviceName: <your_name>-mongo-service
  template:
    metadata:
      labels:
        app: <your_name>-mongo-app
    spec:
      containers:
        - name: <your_name>-mongo-container
          image: mongo:6.0.3
          envFrom:
            - secretRef:
                name: <your_name>-mongo-secrets
          ports:
            - containerPort: 27017
          
          volumeMounts:
            - name: pvc
              mountPath: /data/db
              subPath: <your_name>-mongo-app
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: <your_name>-mongo-pvc

---

apiVersion: v1
kind: Secret
metadata:
  name: <your_name>-mongo-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: dXNlcg==
  MONGO_INITDB_ROOT_PASSWORD: cGFzcw==
